// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "kkitai",
            "url": "https://github.com/kkitai",
            "email": "nmgys043@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/telephones": {
            "get": {
                "description": "returns all telephone informations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telephone"
                ],
                "summary": "list telephone informations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/telephones/{number}": {
            "get": {
                "description": "returns one telephone information by telephone number",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telephone"
                ],
                "summary": "get a telephone information",
                "parameters": [
                    {
                        "minLength": 11,
                        "type": "string",
                        "description": "telephone number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Basic Back-end REST APP in go",
	Description:      "sample implementation of back-end rest api written in go.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
